import pandas as pd
from snakemake.utils import min_version
min_version("7.0")

wrapper_prefix = "https://github.com/snakemake/snakemake-wrappers/raw/master/bio"

configfile: "config/config.yaml"
samples = pd.read_csv(config["samples"], sep="\t", index_col="sample")
SAMPLES = samples.index.tolist()

include: "rules/qc.smk"
include: "rules/assembly.smk"
include: "rules/scaffold.smk"
include: "rules/phylogeny.smk"
include: "rules/variability.smk"


rule all:
    input:
        expand("results/quast/{sample}/report.txt", sample=SAMPLES),
        "results/alignment/mafft_alignment.fasta",
        "results/tree/iqtree.treefile",
        "results/variability/entropy.tsv",
        "results/variability/entropy_plot.png"