# workflow/Snakefile

configfile: "config/config.yaml"

include: "workflow/rules/qc.smk"
include: "workflow/rules/assembly.smk"
include: "workflow/rules/ragtag.smk"        # NEU
include: "workflow/rules/mapping.smk"
include: "workflow/rules/phylogeny.smk"
include: "workflow/rules/variability.smk"

# Targets
rule all:
    input:
        expand("results/tree/{sample}.pdf", sample=config["samples_list"]),
        expand("results/variability/{sample}_entropy.tsv", sample=config["samples_list"]),
        expand("results/variability/{sample}_entropy_plot.png", sample=config["samples_list"]),